import { app, BrowserWindow, ipcMain, dialog } from 'electron';
import * as fs from 'fs';
import * as path from 'path';
import Store from 'electron-store';

// Initialize electron-store for settings
const store = new Store();

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 800,
    width: 1400,
    minHeight: 600,
    minWidth: 800,
    autoHideMenuBar: true,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      nodeIntegration: false,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

// IPC Handlers

// Select folder dialog
ipcMain.handle('select-folder', async () => {
  const result = await dialog.showOpenDialog({
    properties: ['openDirectory', 'createDirectory'],
    title: 'Select Notes Folder',
  });
  
  if (!result.canceled && result.filePaths.length > 0) {
    return result.filePaths[0];
  }
  return null;
});

// List all notes in a folder
ipcMain.handle('list-notes', async (event, folderPath: string) => {
  try {
    if (!fs.existsSync(folderPath)) {
      return [];
    }
    
    const files = fs.readdirSync(folderPath);
    const items = files
      .map(file => {
        const filePath = path.join(folderPath, file);
        const stats = fs.statSync(filePath);
        const isDirectory = stats.isDirectory();
        
        if (isDirectory) {
          // Check if it's a workspace (has .workspace.json)
          const configPath = path.join(filePath, '.workspace.json');
          let workspaceConfig = null;
          
          if (fs.existsSync(configPath)) {
            try {
              const configContent = fs.readFileSync(configPath, 'utf-8');
              workspaceConfig = JSON.parse(configContent);
            } catch (error) {
              console.error('Error reading workspace config:', error);
            }
          }
          
          return {
            name: workspaceConfig ? workspaceConfig.name : file,
            path: filePath,
            modified: stats.mtimeMs,
            isFolder: true,
            isWorkspace: workspaceConfig !== null,
            workspaceColor: workspaceConfig?.color,
          };
        } else if (file.endsWith('.md')) {
          return {
            name: file.replace('.md', ''),
            path: filePath,
            modified: stats.mtimeMs,
            isFolder: false,
          };
        }
        return null;
      })
      .filter(item => item !== null)
      .sort((a, b) => {
        // Sort workspaces first, then notes, then by modified date
        if (a.isWorkspace && !b.isWorkspace) return -1;
        if (!a.isWorkspace && b.isWorkspace) return 1;
        if (a.isFolder && !b.isFolder) return -1;
        if (!a.isFolder && b.isFolder) return 1;
        return b.modified - a.modified;
      });
    
    return items;
  } catch (error) {
    console.error('Error listing notes:', error);
    return [];
  }
});

// Read a note file
ipcMain.handle('read-note', async (event, filePath: string) => {
  try {
    return fs.readFileSync(filePath, 'utf-8');
  } catch (error) {
    console.error('Error reading note:', error);
    return '';
  }
});

// Get all tags from notes in a folder (recursive)
ipcMain.handle('get-all-tags', async (event, folderPath: string) => {
  try {
    const tagsMap: { [tag: string]: Array<{ name: string; path: string }> } = {};
    
    const scanDirectory = (dirPath: string) => {
      const files = fs.readdirSync(dirPath);
      
      for (const file of files) {
        const filePath = path.join(dirPath, file);
        const stats = fs.statSync(filePath);
        
        if (stats.isDirectory()) {
          scanDirectory(filePath); // Recursive scan
        } else if (file.endsWith('.md')) {
          const content = fs.readFileSync(filePath, 'utf-8');
          const tagRegex = /#([a-zA-Z0-9_.-]+)(?=\s|$)/g;
          let match;
          
          while ((match = tagRegex.exec(content)) !== null) {
            const tag = match[1];
            const noteName = file.replace('.md', '');
            
            if (!tagsMap[tag]) {
              tagsMap[tag] = [];
            }
            
            // Avoid duplicates
            if (!tagsMap[tag].find(note => note.path === filePath)) {
              tagsMap[tag].push({ name: noteName, path: filePath });
            }
          }
        }
      }
    };
    
    scanDirectory(folderPath);
    
    return tagsMap;
  } catch (error) {
    console.error('Error getting tags:', error);
    return {};
  }
});

// Search notes by title and content
ipcMain.handle('search-notes', async (event, folderPath: string, query: string) => {
  try {
    const results: Array<{
      name: string;
      path: string;
      isFolder: boolean;
      matchType: 'title' | 'content';
      snippet?: string;
    }> = [];
    
    const searchLower = query.toLowerCase();
    
    const scanDirectory = (dirPath: string) => {
      const files = fs.readdirSync(dirPath);
      
      for (const file of files) {
        const filePath = path.join(dirPath, file);
        const stats = fs.statSync(filePath);
        
        if (stats.isDirectory()) {
          // Check folder name
          if (file.toLowerCase().includes(searchLower)) {
            results.push({
              name: file,
              path: filePath,
              isFolder: true,
              matchType: 'title'
            });
          }
          scanDirectory(filePath); // Recursive scan
        } else if (file.endsWith('.md')) {
          const noteName = file.replace('.md', '');
          
          // Check title match first
          if (noteName.toLowerCase().includes(searchLower)) {
            results.push({
              name: noteName,
              path: filePath,
              isFolder: false,
              matchType: 'title'
            });
          }
          
          // Check content match
          const content = fs.readFileSync(filePath, 'utf-8');
          const contentLower = content.toLowerCase();
          const matchIndex = contentLower.indexOf(searchLower);
          
          if (matchIndex !== -1) {
            // Extract 50 characters before and after the match
            const start = Math.max(0, matchIndex - 50);
            const end = Math.min(content.length, matchIndex + query.length + 50);
            let snippet = content.substring(start, end);
            
            // Add ellipsis if truncated
            if (start > 0) snippet = '...' + snippet;
            if (end < content.length) snippet = snippet + '...';
            
            // Clean up snippet (remove extra whitespace/newlines)
            snippet = snippet.replace(/\s+/g, ' ').trim();
            
            // Only add if not already added by title match
            const existingMatch = results.find(r => r.path === filePath);
            if (!existingMatch) {
              results.push({
                name: noteName,
                path: filePath,
                isFolder: false,
                matchType: 'content',
                snippet
              });
            } else if (existingMatch.matchType === 'title') {
              // Add snippet to existing title match
              existingMatch.snippet = snippet;
            }
          }
        }
      }
    };
    
    scanDirectory(folderPath);
    
    // Sort: title matches first, then content matches
    results.sort((a, b) => {
      if (a.matchType === 'title' && b.matchType === 'content') return -1;
      if (a.matchType === 'content' && b.matchType === 'title') return 1;
      return 0;
    });
    
    return results;
  } catch (error) {
    console.error('Error searching notes:', error);
    return [];
  }
});

// Save a note file
ipcMain.handle('save-note', async (event, filePath: string, content: string) => {
  try {
    fs.writeFileSync(filePath, content, 'utf-8');
  } catch (error) {
    console.error('Error saving note:', error);
    throw error;
  }
});

// Create a new note
ipcMain.handle('create-note', async (event, folderPath: string, title: string) => {
  try {
    // Sanitize title for filename (keep original case, only replace special characters)
    const filename = title.replace(/[^a-zA-Z0-9 ]/g, '_') + '.md';
    const filePath = path.join(folderPath, filename);
    
    // Create file with empty content (no title inside)
    const initialContent = '';
    fs.writeFileSync(filePath, initialContent, 'utf-8');
    
    return filePath;
  } catch (error) {
    console.error('Error creating note:', error);
    throw error;
  }
});

// Create a new workspace
ipcMain.handle('create-workspace', async (event, parentPath: string, workspaceName: string, color: string) => {
  try {
    // Sanitize workspace name
    const sanitizedName = workspaceName.replace(/[^a-zA-Z0-9 ]/g, '_');
    const workspacePath = path.join(parentPath, sanitizedName);
    
    // Create workspace folder if it doesn't exist
    if (!fs.existsSync(workspacePath)) {
      fs.mkdirSync(workspacePath, { recursive: true });
    }
    
    // Create workspace config file
    const configPath = path.join(workspacePath, '.workspace.json');
    const config = {
      name: workspaceName,
      color: color,
      createdAt: Date.now(),
    };
    fs.writeFileSync(configPath, JSON.stringify(config, null, 2), 'utf-8');
    
    return workspacePath;
  } catch (error) {
    console.error('Error creating workspace:', error);
    throw error;
  }
});

// Get workspace config
ipcMain.handle('get-workspace-config', async (event, workspacePath: string) => {
  try {
    const configPath = path.join(workspacePath, '.workspace.json');
    
    if (fs.existsSync(configPath)) {
      const configContent = fs.readFileSync(configPath, 'utf-8');
      return JSON.parse(configContent);
    }
    
    return null;
  } catch (error) {
    console.error('Error reading workspace config:', error);
    return null;
  }
});

// Update workspace config
ipcMain.handle('update-workspace-config', async (event, workspacePath: string, name: string, color: string) => {
  try {
    const configPath = path.join(workspacePath, '.workspace.json');
    
    let config: any = {
      createdAt: Date.now(),
    };
    
    // Read existing config if it exists
    if (fs.existsSync(configPath)) {
      const configContent = fs.readFileSync(configPath, 'utf-8');
      config = JSON.parse(configContent);
    }
    
    // Update config
    config.name = name;
    config.color = color;
    config.updatedAt = Date.now();
    
    fs.writeFileSync(configPath, JSON.stringify(config, null, 2), 'utf-8');
    
    return config;
  } catch (error) {
    console.error('Error updating workspace config:', error);
    throw error;
  }
});

// Delete a note
ipcMain.handle('delete-note', async (event, filePath: string) => {
  try {
    fs.unlinkSync(filePath);
  } catch (error) {
    console.error('Error deleting note:', error);
    throw error;
  }
});

// Delete a folder and all its contents
ipcMain.handle('delete-folder', async (event, folderPath: string) => {
  try {
    // Recursively delete folder and all contents
    fs.rmSync(folderPath, { recursive: true, force: true });
  } catch (error) {
    console.error('Error deleting folder:', error);
    throw error;
  }
});

// Move a note to a folder
ipcMain.handle('move-note', async (event, notePath: string, targetFolderPath: string) => {
  try {
    const fileName = path.basename(notePath);
    const newPath = path.join(targetFolderPath, fileName);
    
    // Check if file already exists in target folder
    if (fs.existsSync(newPath)) {
      throw new Error('A file with this name already exists in the target folder');
    }
    
    // Move the file
    fs.renameSync(notePath, newPath);
    
    return newPath;
  } catch (error) {
    console.error('Error moving note:', error);
    throw error;
  }
});

// Rename a note
ipcMain.handle('rename-note', async (event, oldPath: string, newTitle: string) => {
  try {
    console.log('=== RENAME DEBUG ===');
    console.log('Input newTitle:', newTitle);
    console.log('newTitle type:', typeof newTitle);
    console.log('oldPath:', oldPath);
    
    const folderPath = path.dirname(oldPath);
    // Sanitize title for filename (keep original case, only replace special characters)
    const filename = newTitle.replace(/[^a-zA-Z0-9 ]/g, '_') + '.md';
    console.log('Generated filename:', filename);
    
    const newPath = path.join(folderPath, filename);
    console.log('Full new path:', newPath);
    
    // Only rename if the new path is different
    if (oldPath !== newPath) {
      // Check if a file with the new name already exists
      if (fs.existsSync(newPath)) {
        console.error('File already exists:', newPath);
        throw new Error('A note with this name already exists');
      }
      console.log('Executing rename...');
      fs.renameSync(oldPath, newPath);
      console.log('Rename complete');
      
      // Verify the actual filename on disk
      const actualFiles = fs.readdirSync(folderPath);
      console.log('Files in directory after rename:', actualFiles);
    } else {
      console.log('Paths are the same, no rename needed');
    }
    
    return newPath;
  } catch (error) {
    console.error('Error renaming note:', error);
    throw error;
  }
});

// Get setting
ipcMain.handle('get-setting', async (event, key: string) => {
  return store.get(key);
});

// Set setting
ipcMain.handle('set-setting', async (event, key: string, value: any) => {
  store.set(key, value);
});

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
