import { app, BrowserWindow, ipcMain, dialog } from 'electron';
import * as fs from 'fs';
import * as path from 'path';
import Store from 'electron-store';

// Initialize electron-store for settings
const store = new Store();

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 800,
    width: 1400,
    minHeight: 600,
    minWidth: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      nodeIntegration: false,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

// IPC Handlers

// Select folder dialog
ipcMain.handle('select-folder', async () => {
  const result = await dialog.showOpenDialog({
    properties: ['openDirectory', 'createDirectory'],
    title: 'Select Notes Folder',
  });
  
  if (!result.canceled && result.filePaths.length > 0) {
    return result.filePaths[0];
  }
  return null;
});

// List all notes in a folder
ipcMain.handle('list-notes', async (event, folderPath: string) => {
  try {
    if (!fs.existsSync(folderPath)) {
      return [];
    }
    
    const files = fs.readdirSync(folderPath);
    const notes = files
      .filter(file => file.endsWith('.md'))
      .map(file => {
        const filePath = path.join(folderPath, file);
        const stats = fs.statSync(filePath);
        return {
          name: file.replace('.md', ''),
          path: filePath,
          modified: stats.mtimeMs,
        };
      })
      .sort((a, b) => b.modified - a.modified); // Sort by most recent
    
    return notes;
  } catch (error) {
    console.error('Error listing notes:', error);
    return [];
  }
});

// Read a note file
ipcMain.handle('read-note', async (event, filePath: string) => {
  try {
    return fs.readFileSync(filePath, 'utf-8');
  } catch (error) {
    console.error('Error reading note:', error);
    return '';
  }
});

// Save a note file
ipcMain.handle('save-note', async (event, filePath: string, content: string) => {
  try {
    fs.writeFileSync(filePath, content, 'utf-8');
  } catch (error) {
    console.error('Error saving note:', error);
    throw error;
  }
});

// Create a new note
ipcMain.handle('create-note', async (event, folderPath: string, title: string) => {
  try {
    // Sanitize title for filename (keep original case, only replace special characters)
    const filename = title.replace(/[^a-zA-Z0-9 ]/g, '_') + '.md';
    const filePath = path.join(folderPath, filename);
    
    // Create file with empty content (no title inside)
    const initialContent = '';
    fs.writeFileSync(filePath, initialContent, 'utf-8');
    
    return filePath;
  } catch (error) {
    console.error('Error creating note:', error);
    throw error;
  }
});

// Delete a note
ipcMain.handle('delete-note', async (event, filePath: string) => {
  try {
    fs.unlinkSync(filePath);
  } catch (error) {
    console.error('Error deleting note:', error);
    throw error;
  }
});

// Rename a note
ipcMain.handle('rename-note', async (event, oldPath: string, newTitle: string) => {
  try {
    console.log('=== RENAME DEBUG ===');
    console.log('Input newTitle:', newTitle);
    console.log('newTitle type:', typeof newTitle);
    console.log('oldPath:', oldPath);
    
    const folderPath = path.dirname(oldPath);
    // Sanitize title for filename (keep original case, only replace special characters)
    const filename = newTitle.replace(/[^a-zA-Z0-9 ]/g, '_') + '.md';
    console.log('Generated filename:', filename);
    
    const newPath = path.join(folderPath, filename);
    console.log('Full new path:', newPath);
    
    // Only rename if the new path is different
    if (oldPath !== newPath) {
      // Check if a file with the new name already exists
      if (fs.existsSync(newPath)) {
        console.error('File already exists:', newPath);
        throw new Error('A note with this name already exists');
      }
      console.log('Executing rename...');
      fs.renameSync(oldPath, newPath);
      console.log('Rename complete');
      
      // Verify the actual filename on disk
      const actualFiles = fs.readdirSync(folderPath);
      console.log('Files in directory after rename:', actualFiles);
    } else {
      console.log('Paths are the same, no rename needed');
    }
    
    return newPath;
  } catch (error) {
    console.error('Error renaming note:', error);
    throw error;
  }
});

// Get setting
ipcMain.handle('get-setting', async (event, key: string) => {
  return store.get(key);
});

// Set setting
ipcMain.handle('set-setting', async (event, key: string, value: any) => {
  store.set(key, value);
});

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
